/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CriadoresParceirosRouteImport } from './routes/criadores-parceiros'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge/$slug'
import { Route as FilaServiceRouteImport } from './routes/fila.$service'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'
import { Route as CheckoutCanceladoRouteImport } from './routes/checkout.cancelado'
import { Route as CheckoutServiceRouteImport } from './routes/checkout.$service'
import { Route as ApoiarAppRouteImport } from './routes/apoiar.$app'
import { Route as KnowledgeSlugChapterRouteImport } from './routes/knowledge/$slug.$chapter'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicDownloadsPackImagensPremiumDotzipRouteImport } from './routes/api/public/downloads/pack-imagens-premium[.]zip'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CriadoresParceirosRoute = CriadoresParceirosRouteImport.update({
  id: '/criadores-parceiros',
  path: '/criadores-parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/knowledge/$slug',
  path: '/knowledge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaServiceRoute = FilaServiceRouteImport.update({
  id: '/fila/$service',
  path: '/fila/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/checkout/sucesso',
  path: '/checkout/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCanceladoRoute = CheckoutCanceladoRouteImport.update({
  id: '/checkout/cancelado',
  path: '/checkout/cancelado',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutServiceRoute = CheckoutServiceRouteImport.update({
  id: '/checkout/$service',
  path: '/checkout/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoiarAppRoute = ApoiarAppRouteImport.update({
  id: '/apoiar/$app',
  path: '/apoiar/$app',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugChapterRoute = KnowledgeSlugChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => KnowledgeSlugRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadsPackImagensPremiumDotzipRoute =
  ApiPublicDownloadsPackImagensPremiumDotzipRouteImport.update({
    id: '/api/public/downloads/pack-imagens-premium.zip',
    path: '/api/public/downloads/pack-imagens-premium.zip',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/criadores-parceiros': typeof CriadoresParceirosRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/apoiar/$app': typeof ApoiarAppRoute
  '/checkout/$service': typeof CheckoutServiceRoute
  '/checkout/cancelado': typeof CheckoutCanceladoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/fila/$service': typeof FilaServiceRoute
  '/knowledge/$slug': typeof KnowledgeSlugRouteWithChildren
  '/knowledge/': typeof KnowledgeIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/knowledge/$slug/$chapter': typeof KnowledgeSlugChapterRoute
  '/api/public/downloads/pack-imagens-premium.zip': typeof ApiPublicDownloadsPackImagensPremiumDotzipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/criadores-parceiros': typeof CriadoresParceirosRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/apoiar/$app': typeof ApoiarAppRoute
  '/checkout/$service': typeof CheckoutServiceRoute
  '/checkout/cancelado': typeof CheckoutCanceladoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/fila/$service': typeof FilaServiceRoute
  '/knowledge/$slug': typeof KnowledgeSlugRouteWithChildren
  '/knowledge': typeof KnowledgeIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/knowledge/$slug/$chapter': typeof KnowledgeSlugChapterRoute
  '/api/public/downloads/pack-imagens-premium.zip': typeof ApiPublicDownloadsPackImagensPremiumDotzipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/criadores-parceiros': typeof CriadoresParceirosRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/apoiar/$app': typeof ApoiarAppRoute
  '/checkout/$service': typeof CheckoutServiceRoute
  '/checkout/cancelado': typeof CheckoutCanceladoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/fila/$service': typeof FilaServiceRoute
  '/knowledge/$slug': typeof KnowledgeSlugRouteWithChildren
  '/knowledge/': typeof KnowledgeIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/knowledge/$slug/$chapter': typeof KnowledgeSlugChapterRoute
  '/api/public/downloads/pack-imagens-premium.zip': typeof ApiPublicDownloadsPackImagensPremiumDotzipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/auth'
    | '/biblioteca'
    | '/criadores-parceiros'
    | '/faq'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/apoiar/$app'
    | '/checkout/$service'
    | '/checkout/cancelado'
    | '/checkout/sucesso'
    | '/fila/$service'
    | '/knowledge/$slug'
    | '/knowledge/'
    | '/api/public/stripe-webhook'
    | '/knowledge/$slug/$chapter'
    | '/api/public/downloads/pack-imagens-premium.zip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/auth'
    | '/biblioteca'
    | '/criadores-parceiros'
    | '/faq'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/apoiar/$app'
    | '/checkout/$service'
    | '/checkout/cancelado'
    | '/checkout/sucesso'
    | '/fila/$service'
    | '/knowledge/$slug'
    | '/knowledge'
    | '/api/public/stripe-webhook'
    | '/knowledge/$slug/$chapter'
    | '/api/public/downloads/pack-imagens-premium.zip'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/auth'
    | '/biblioteca'
    | '/criadores-parceiros'
    | '/faq'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/apoiar/$app'
    | '/checkout/$service'
    | '/checkout/cancelado'
    | '/checkout/sucesso'
    | '/fila/$service'
    | '/knowledge/$slug'
    | '/knowledge/'
    | '/api/public/stripe-webhook'
    | '/knowledge/$slug/$chapter'
    | '/api/public/downloads/pack-imagens-premium.zip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CriadoresParceirosRoute: typeof CriadoresParceirosRoute
  FaqRoute: typeof FaqRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  ApoiarAppRoute: typeof ApoiarAppRoute
  CheckoutServiceRoute: typeof CheckoutServiceRoute
  CheckoutCanceladoRoute: typeof CheckoutCanceladoRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
  FilaServiceRoute: typeof FilaServiceRoute
  KnowledgeSlugRoute: typeof KnowledgeSlugRouteWithChildren
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicDownloadsPackImagensPremiumDotzipRoute: typeof ApiPublicDownloadsPackImagensPremiumDotzipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criadores-parceiros': {
      id: '/criadores-parceiros'
      path: '/criadores-parceiros'
      fullPath: '/criadores-parceiros'
      preLoaderRoute: typeof CriadoresParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/knowledge/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila/$service': {
      id: '/fila/$service'
      path: '/fila/$service'
      fullPath: '/fila/$service'
      preLoaderRoute: typeof FilaServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/checkout/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancelado': {
      id: '/checkout/cancelado'
      path: '/checkout/cancelado'
      fullPath: '/checkout/cancelado'
      preLoaderRoute: typeof CheckoutCanceladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$service': {
      id: '/checkout/$service'
      path: '/checkout/$service'
      fullPath: '/checkout/$service'
      preLoaderRoute: typeof CheckoutServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoiar/$app': {
      id: '/apoiar/$app'
      path: '/apoiar/$app'
      fullPath: '/apoiar/$app'
      preLoaderRoute: typeof ApoiarAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug/$chapter': {
      id: '/knowledge/$slug/$chapter'
      path: '/$chapter'
      fullPath: '/knowledge/$slug/$chapter'
      preLoaderRoute: typeof KnowledgeSlugChapterRouteImport
      parentRoute: typeof KnowledgeSlugRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/downloads/pack-imagens-premium.zip': {
      id: '/api/public/downloads/pack-imagens-premium.zip'
      path: '/api/public/downloads/pack-imagens-premium.zip'
      fullPath: '/api/public/downloads/pack-imagens-premium.zip'
      preLoaderRoute: typeof ApiPublicDownloadsPackImagensPremiumDotzipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KnowledgeSlugRouteChildren {
  KnowledgeSlugChapterRoute: typeof KnowledgeSlugChapterRoute
}

const KnowledgeSlugRouteChildren: KnowledgeSlugRouteChildren = {
  KnowledgeSlugChapterRoute: KnowledgeSlugChapterRoute,
}

const KnowledgeSlugRouteWithChildren = KnowledgeSlugRoute._addFileChildren(
  KnowledgeSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  CriadoresParceirosRoute: CriadoresParceirosRoute,
  FaqRoute: FaqRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  ApoiarAppRoute: ApoiarAppRoute,
  CheckoutServiceRoute: CheckoutServiceRoute,
  CheckoutCanceladoRoute: CheckoutCanceladoRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
  FilaServiceRoute: FilaServiceRoute,
  KnowledgeSlugRoute: KnowledgeSlugRouteWithChildren,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicDownloadsPackImagensPremiumDotzipRoute:
    ApiPublicDownloadsPackImagensPremiumDotzipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
